### ISSUE TITLE
How to define a nodeView( vue component ) with content ? 

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#296]
I tried, but i can NOT edit text as expect, cuz the cursor's position is not right.

```vue
Paragraph.vue

<template>
    <p ref="content"></p>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class ParagraphView extends Vue {
    @Prop() private node!: any;
    @Prop() private updateAttrs!: () => void;
    @Prop() private editable!: boolean;
}
</script>

<style lang="stylus" scoped>

</style>


```

```javascript
Paragraph.js

import { Node } from 'tiptap';
import { setBlockType } from 'tiptap-commands';
import ParagraphView from 'Paragraph.vue';

export default class Paragraph extends Node {

    get name() {
        return 'paragraph'
    }

    get schema() {
        return {
            content: 'inline*',
            group: 'block',
            draggable: false,
            parseDOM: [{
                tag: 'p',
            }],
            toDOM: () => ['p', 0],
        }
    }

    commands({ type }) {
        return () => setBlockType(type)
    }

    get view() {
        return ParagraphView
      }
}
```

### Screenshots
![4444](https://user-images.githubusercontent.com/13865581/57303661-61753f00-7110-11e9-82e7-9e834ee4c154.gif)

**Comment by dSolid** [comment]
I'm having the same issue as you with a component I made. Except it was actually working a before (and I still get it to work on old versions) and broke recently.

**Comment by Alecyrus** [comment]
Could you specific the latest version that works against this issue？

**Comment by dSolid** [comment]
Its on a computer that didnt run npm install in a while, the tiptap version on there is 1.16.2.

**Comment by Alecyrus** [comment]
It  seems like a bad way to use `nodeView`, cuz it brings extra cost when handling inline node.

**Comment by Alecyrus** [comment]
Probably I figure it out, but i am not going to forward the thread.
The following code may help if you need.
```vue

<template>
    <div class="root" contenteditable="false">
        <code ref="content" contenteditable="true"></code>
    </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class CodeblockView extends Vue {
    @Prop() private node!: any;
    @Prop() private updateAttrs!: (arg: any) => void;
}
</script>
<style lang="stylus" scoped></style>
```


```javascript
 get view() {
    return CodeblockView
  }
```

**Comment by philippkuehn** [comment]
This seems to be a bug and should be fixed in the latest version.

**Comment by Hendrixer** [comment]
@philippkuehn what release was this fixed in, I'm still having this issue with version `1.20.0`

**Comment by philippkuehn** [comment]
This sounds like an version problem. Remove your node modules folder and yarn lock file and make a fresh install.

**Comment by Hendrixer** [comment]
@philippkuehn just did so. Still having the issue where the cursor is jumping around. Not sure if I'm missing something or if this is another bug. Here is the template of the component being using in the view of a Node. There is no logic in the component, just this template and prop definitions.
```html
<template>
  <div class="code-node">
    <pre
      contenteditable="false"
    ><code ref="content" :contenteditable="view.editable.toString()"></code></pre>
  </div>
</template>
<script>
```

**Comment by philippkuehn** [comment]
@Hendrixer hmm, I can reproduce this. It seems that ProseMirror behave different in code blocks here. Without the contendeditable attributes it's working fine for me.

```vue
<template>
  <div class="code-node">
    <pre><code ref="content"></code></pre>
  </div>
</template>
```

**Comment by Hendrixer** [comment]
strange. will try that instead. Thanks for the help
